go: go1.1.1

after_checkout:
  - "mkdir -p $GOPATH/src"
  - "mv $CI_BUILD_PATH $GOPATH/src/"
  - "export CI_BUILD_PATH $GOPATH/src/bundle_cache"

install:
  - "go env"
  - "go get"

script:
  - "./build"
